# Dependency Review Action
#
# This Action will scan dependency manifest files that change as part of a Pull Request,
# surfacing known-vulnerable versions of the packages declared or updated in the PR.
# Once installed, if the workflow run is marked as required,
# PRs introducing known-vulnerable packages will be blocked from merging.
#
# Source repository: https://github.com/actions/dependency-review-action
name: 'Dependency Review'
on: [pull_request]

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
        with:
          egress-policy: audit

      - name: 'Checkout Repository'
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@4081bf99e2866ebe428fc0477b69eb4fcda7220a # v4.4.0
        with:
          allow-ghsas: >-
            GHSA-52cp-r559-cp3m,
            GHSA-5p4m-2wfm-xmqj,
            GHSA-h67p-54hq-rp68,
            GHSA-mh29-5h37-fv8m,
            GHSA-w5hq-g745-h8pq,
            GHSA-4w7w-66w2-5vf9,
            GHSA-93m4-6634-74q7,
            GHSA-c27g-q93r-2cwf,
            GHSA-fx2h-pf6j-xcff,
            GHSA-g4jq-h2w9-997c,
            GHSA-jqfw-vq24-v9c3,
            GHSA-v6wh-96g9-6wx3,
            GHSA-5xrq-8626-4rwp,
            GHSA-67mh-4wv8-2f99
