on:
  issues:
    types: [opened]

name: Issue opened

jobs:
  assignAuthor:
    name: Assign author to issue
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          egress-policy: audit

      - uses: step-security/assign-author@0cb7e35d4ca01a9330f73ef99e4b271b9baca7cb # main
