on:
  pull_request_target:
    types: [opened]

name: Pull Request opened

jobs:
  assignAuthor:
    name: Assign author to PR
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
        with:
          egress-policy: audit

      - uses: step-security/assign-author@172c40c0e4003f78b4e8df61b4382ffcf3fa3c31 # main